### ISSUE TITLE
相対オクターブ記号についてのオプション

### ISSUE THREAD

**Issue by b2ox** [ksasao/mml2neutrino#2]
相対オクターブの種類を選ぶオプションもあると良いかなと思います。
現在のはPC98系統の相対オクターブで>:+1, <:-1なわけですけど、
X68k系統だと逆に<:+1, >:-1ですし。

**Comment by ksasao** [comment]
[ピコカキコ](https://dic.nicovideo.jp/a/%E3%83%8B%E3%82%B3%E3%83%8B%E3%82%B3%E5%A4%A7%E7%99%BE%E7%A7%91%3A%E3%83%94%E3%82%B3%E3%82%AB%E3%82%AD%E3%82%B3%E3%83%98%E3%83%AB%E3%83%97)も逆なので、オプションで対応できるとよさそうですね。次回アップデートで対応します。

**Comment by b2ox** [comment]
実装されたようなので閉じておきますね。
お疲れさまです。
